sudo: required

language: java

notifications:
  email: false

jdk:
  - oraclejdk8

before_install:
   - chmod +x ./mvnw

script: mvn clean verify

deploy:  
skip_cleanup: true  
provider: heroku  
api_key: $HEROKU_API_KEY  
app:    master: currency-converter
