sudo: required

language: java

notifications:
    slack: currency-converter:TwXn4RFCPjUOLRKijvn3jON8

jdk:
  - oraclejdk8

before_install:
   - chmod +x ./mvnw

script: mvn clean verify

after_success:
  - mvn clean test jacoco:report coveralls:report

